"""Add Institution and query history fields

Revision ID: 6dc25d26cc7a
Revises: e931a2a100ff
Create Date: 2026-05-27 13:35:15.607658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc25d26cc7a'
down_revision: Union[str, None] = 'e931a2a100ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_domain'), 'institutions', ['domain'], unique=False)
    op.create_foreign_key(None, 'clinical_feedback', 'query_history', ['query_id'], ['id'])
    op.add_column('query_history', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.add_column('query_history', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('query_history', sa.Column('query_protocol', sa.String(length=255), nullable=True))
    op.add_column('query_history', sa.Column('risk_status', sa.String(length=50), nullable=True))
    op.add_column('query_history', sa.Column('anomaly_reason', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_query_history_institution_id'), 'query_history', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'query_history', 'institutions', ['institution_id'], ['id'])
    op.add_column('users', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'institution_id')
    op.drop_constraint(None, 'query_history', type_='foreignkey')
    op.drop_index(op.f('ix_query_history_institution_id'), table_name='query_history')
    op.drop_column('query_history', 'anomaly_reason')
    op.drop_column('query_history', 'risk_status')
    op.drop_column('query_history', 'query_protocol')
    op.drop_column('query_history', 'ip_address')
    op.drop_column('query_history', 'institution_id')
    op.drop_constraint(None, 'clinical_feedback', type_='foreignkey')
    op.drop_index(op.f('ix_institutions_domain'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
